-- MIXINS --

local Credits = {

	{
		ttop = "crazy",
		tbottom = "stairs",
	},
	{
		ttop = "game",
		bottom = "sleazel",
	},
	{
		ttop = "models",
		bottom = "Gambler2022",
	},
	{
		ttop = "icons",
		bottom = "_doodleboi",
	},
	{
		ttop = "boxes",
		bottom = "@wwwtyro",
	},
	{
		ttop = "data",
		bottom = "loleris",
	},
	{
		ttop = "translators",
		bottom = "",
	},
	{
		top = "ITALIANO",
		bottom = "Roloversion & Pio_Centorame",
	},
	{
		top = "MAGYAR",
		bottom = "Wortox_SzM",
	},
	{
		top = "РУССКИЙ",
		bottom = "Lapuskus86, Arnie_skunk & v01d_1ncept10n",
	},
	{
		ttop = "testers",
		bottom = "",
	},
	{
		top = "SpuddyBuddy3913",
		bottom = "That1Dummy",
	},
	{
		top = "Roloversion",
		bottom = "Ondrik132",
	},
	{
		top = "dabsforlif",
		bottom = "iiBIuestar",
	},
	{
		top = "lullwaves",
		bottom = "TDtheTV",
	},
	{
		top = "BAsniper2",
		bottom = "d4vvd",
	},
	{
		top = "portalgunner",
		bottom = "DragonMaster1707",
	},
	{
		top = "wf_sh",
		bottom = "Keysiries",
	},
	{
		top = "jakmat2",
		bottom = "blankeht",
	},
	{
		top = "ben10beg",
		bottom = "bash1234567888",
	},
	{
		top = "levthelioin123",
		bottom = "EclipseCashier",
	},
	{
		top = "MightyDantheman",
		bottom = "Noobiest753",
	},
	{
		top = "Dasher89798",
		bottom = "ian12641",
	},
	{
		top = "SoulStealer22",
		bottom = "A_CorruptedEntity",
	},
	{
		top = "Wortox_SzM",
		bottom = "dude567329",
	},
	{
		ttop = "thanks",
		bottom = "",
	},
	{
		top = "kolcer",
		bottom = "cakegirlserina",
	},
	{
		top = "ThatTimothy",
		bottom = "SerpentineKing",
	},
	{
		top = "WhereDidTheSunGo",
		bottom = "b3ntheplay3r2",
	},
	{
		top = "TehEpix2",
		bottom = "Narvog1",
	},
	{
		top = "Shark66655",
		bottom = "Kampfkarren",
	},
	{
		ttop = "music",
		bottom = "",
	},
	{
		top = "TUTORIAL",
		tbottom = "climb",
	},
	{
		top = "Fantazia",
		bottom = "Shahrooz Raoofi",
	},
	{
		top = "TUTORIAL",
		tbottom = "endgame",
	},
	{
		top = "Filth and Fury",
		bottom = "Shahrooz Raoofi",
	},
	{
		top = "MUGGLE",
		tbottom = "climb",
	},
	{
		top = "Gathering Storm",
		bottom = "Gary Scargill & Peter Oldroyd",
	},
	{
		top = "MUGGLE",
		tbottom = "endgame",
	},
	{
		top = "Reflections",
		bottom = "Milan Pillar",
	},
	{
		top = "HACKER",
		tbottom = "climb",
	},
	{
		top = "Network",
		bottom = "Gary Scargill & Peter Oldroyd",
	},
	{
		top = "HACKER",
		tbottom = "endgame",
	},
	{
		top = "Descending Into Oblivion",
		bottom = "Richard Preston",
	},
	{
		top = "WICKED",
		tbottom = "climb",
	},
	{
		top = "Wicked",
		bottom = "Jay Nielsen & Nathan Duvall",
	},
	{
		top = "WICKED",
		tbottom = "endgame",
	},
	{
		top = "Something Wicked",
		bottom = "Cris Velasco",
	},
	{
		top = "KEEPER",
		tbottom = "climb",
	},
	{
		top = "Automotion",
		bottom = "Gary Scargill & Peter Oldroyd",
	},
	{
		top = "KEEPER",
		tbottom = "endgame",
	},
	{
		top = "Synth On The Highway",
		bottom = "Richard Preston",
	},
	{
		top = "GREMLIN",
		tbottom = "climb",
	},
	{
		top = "Death after Life",
		bottom = "Jonathan Pilcher",
	},
	{
		top = "GREMLIN",
		tbottom = "endgame",
	},
	{
		top = "Fantastical Waltz",
		bottom = "Claire Batchelor",
	},
	{
		top = "JOKER",
		tbottom = "climb",
	},
	{
		top = "Call 911",
		bottom = "Bret Levick, Robert Navarro & Sven Spieker",
	},
	{
		top = "JOKER",
		tbottom = "endgame",
	},
	{
		top = "Fender Stab",
		bottom = "Steven Bush",
	},
	{
		top = "DRIFTER",
		tbottom = "climb",
	},
	{
		top = "Communique",
		bottom = "Gary Scargill & Peter Oldroyd",
	},
	{
		top = "DRIFTER",
		tbottom = "endgame",
	},
	{
		top = "Fragile",
		bottom = "Gary Scargill & Peter Oldroyd",
	},
	{
		top = "SPLICER",
		tbottom = "climb",
	},
	{
		top = "Unlimited Power",
		bottom = "Laurent Lombart",
	},
	{
		top = "SPLICER",
		tbottom = "endgame",
	},
	{
		top = "Unlimited Power",
		bottom = "Epic Score",
	},
	{
		top = "PATRON",
		tbottom = "climb",
	},
	{
		top = "Tranquilize",
		bottom = "Gary Scargill & Peter Oldroyd",
	},
	{
		top = "PATRON",
		tbottom = "endgame",
	},
	{
		top = "Dreamers",
		bottom = "Jospeh Alexander",
	},
	{
		top = "ARCHON",
		tbottom = "climb",
	},
	{
		top = "Aperture",
		bottom = "Paul Emons, Richard Goodliff & Ian Robson",
	},
	{
		top = "ARCHON",
		tbottom = "endgame",
	},
	{
		top = "Rendezvous",
		bottom = "Paul Emons, Richard Goodliff & Ian Robson",
	},
	{
		top = "SPECTRE",
		tbottom = "climb",
	},
	{
		top = "Reflections",
		bottom = "Gary Scargill & Peter Oldroyd",
	},
	{
		top = "SPECTRE",
		tbottom = "endgame",
	},
	{
		top = "Cosmic Dust",
		bottom = "Milan Pilar",
	},
	{
		top = "THIEF",
		tbottom = "climb",
	},
	{
		top = "Reaching Out",
		bottom = "Gary Scargill & Peter Oldroyd",
	},
	{
		top = "THIEF",
		tbottom = "endgame",
	},
	{
		top = "Soaring",
		bottom = "Richard Preston",
	},
	{
		top = "REAVER",
		tbottom = "climb",
	},
	{
		top = "Hopeful Chillstep",
		bottom = "AXS Music",
	},
	{
		top = "REAVER",
		tbottom = "endgame",
	},
	{
		top = "The Squad",
		bottom = "Bob Bradley",
	},
	{
		top = "HERETIC",
		tbottom = "climb",
	},
	{
		top = "Mother",
		bottom = "Gary Scargill & Peter Oldroyd",
	},
	{
		top = "HERETIC",
		tbottom = "endgame",
	},
	{
		top = "Being Me",
		bottom = "Gary Scargill & Peter Oldroyd",
	},
	{
		top = "NECROMANCER",
		tbottom = "climb",
	},
	{
		top = "Forest Twilight",
		bottom = "Jonathan Pilcher",
	},
	{
		top = "NECROMANCER",
		tbottom = "endgame",
	},
	{
		top = "Darkness",
		bottom = "Lawrence Oakley",
	},
	{
		top = "CHAMELEON",
		tbottom = "climb",
	},
	{
		top = "Rah",
		bottom = "Gary Scargill & Peter Oldroyd",
	},
	{
		top = "CHAMELEON",
		tbottom = "endgame",
	},
	{
		top = "Midnight Runner",
		bottom = "Richard Preston",
	},
	{
		top = "POSSESSED",
		tbottom = "climb",
	},
	{
		top = "Dark Souls",
		bottom = "David Arkenstone",
	},
	{
		top = "POSSESSED",
		tbottom = "endgame",
	},
	{
		top = "Deceived",
		bottom = "Martin Sponticcia",
	},
	{
		top = "HYPNOTISED",
		tbottom = "climb",
	},
	{
		top = "Cloak and Dagger",
		bottom = "Claire Batchelor",
	},
	{
		top = "HYPNOTISED",
		tbottom = "endgame",
	},
	{
		top = "No Questions Asked",
		bottom = "Gregor F. Narholz",
	},
	{
		top = "REFLECTED",
		tbottom = "climb",
	},
	{
		top = "Delicate Chillstep",
		bottom = "AXS Music",
	},
	{
		top = "REFLECTED",
		tbottom = "endgame",
	},
	{
		top = "Dark Meditation",
		bottom = "Ellis Dews & Willie Eaglin",
	},
	{
		top = "ARCHITECT",
		tbottom = "climb",
	},
	{
		top = "Secrets and Shadows",
		bottom = "Gary Scargill & Peter Oldroyd",
	},
	{
		ttop = "ghost",
		bottom = "",
	},
	{
		top = "Amber Garden",
		bottom = "Paul Emons, Richard Goodliff & Ian Robson",
	},
	{
		ttop = "disco",
		bottom = "",
	},
	{
		top = "To the Disco",
		bottom = "Gordon Zola",
	},
	{
		ttop = "elevator",
		bottom = "",
	},
	{
		top = "Radioactivity",
		bottom = "Gary Scargill & Peter Oldroyd",
	},
	{
		top = "NONE",
		tbottom = "climb",
	},
	{
		top = "Allure",
		bottom = "Martin Sponticcia",
	},
	{
		top = "NONE",
		tbottom = "endgame",
	},
	{
		top = "Gathering Storm",
		bottom = "Adam Saunders, Mark Cousins & Christopher Salt",
	},
	{
		ttop = "finish",
		bottom = "",
	},



}


-- CONSTANTS --

-- ELEMENTS --

-- VARIABLES --

-- REMOTES --

-- LOCALS --

-- PRIVATES --

-- PUBLICS --

-- PREPARATION --

return Credits
